/*! --
// (c) Mario Dentone 2019
---------------------- */

(function() {
    window.strings = window.strings || {};
    strings['it'] = {

        PAGETITLE: 'League of Legends Teamfight Tactics | GUIDA AGLI OGGETTI',

        BASEITEMS: 'Oggetti base',
        COMBITEMS: 'Oggetti combinati',
        CHAMPIONS: 'Campioni',

        // Base Items:
        SWORD_NAME: "M.C. spada",
        SWORD_DESC: "+20 attacco fisico.",
        BOW_NAME: "Arco ricurvo",
        BOW_DESC: "+20% velocità di attacco.",
        ROD_NAME: "Bastone colossale",
        ROD_DESC: "+20% potenza abilità.",
        TEAR_NAME: "Lacrima della dea",
        TEAR_DESC: "+20 mana.",
        VEST_NAME: "Cotta di maglia",
        VEST_DESC: "+20 armatura.",
        CLOAK_NAME: "Mantello di Negatron",
        CLOAK_DESC: "+20 resistenza magica.",
        BELT_NAME: "Cintura del gigante",
        BELT_DESC: "+200 salute.",
        SPATULA_NAME: "Spatola",
        SPATULA_DESC: "Deve fare _qualcosa_ ...",

        // Combined Items:
        DEATHBLADE_NAME: "Lama mortale",
        DEATHBLADE_DESC: "Dopo un'eliminazione, guadagna una M.C. Spada per il resto del round (occupa 3 slot oggetti).",
        LASTWHISPER_NAME: "Sussurro fatale",
        LASTWHISPER_DESC: "Gli attacchi non possono andare a vuoto e infliggono il 5% della salute massima del bersaglio in danni puri.",
        GUNBLADE_NAME: "Pistola a lame hextech",
        GUNBLADE_DESC: "Attacchi base e abilità lanciate curano il portatore per il 25% dei danni inflitti.",
        SPEAR_NAME: "Lancia di Shojin",
        SPEAR_DESC: "Dopo il lancio di un'abilità, gli attacchi base del portatore recuperano 15% del mana massimo.",
        ANGEL_NAME: "Angelo custode",
        ANGEL_DESC: "Il portatore, alla morte, si purifica dagli effetti negativi e risorge con un massimo di 500 salute dopo 2 secondi. Si attiva una volta per combattimento.",
        BLOODTHIRSTER_NAME: "La Bramasangue",
        BLOODTHIRSTER_DESC: "Infliggere danni fisici cura il portatore per il 33% dei danni inflitti.",
        HERALD_NAME: "Araldo di Zeke",
        HERALD_DESC: "All'inizio del combattimento, il portatore e i suoi alleati nella stessa fila entro 2 esagoni ottengono +15% di velocità d'attacco per il resto del combattimento.",
        GHOSTBLADE_NAME: "Lama di Youmuu",
        GHOSTBLADE_DESC: "AD +20 in più. Il portatore è anche un Assassino.",
        FIRECANNON_NAME: "Archibugio a ripetizione",
        FIRECANNON_DESC: "Il portatore guadagna +100% Gittata d'attacco e non è possibile schivare i suoi attacchi base.",
        RAGEBLADE_NAME: "Furia di Guinsoo",
        RAGEBLADE_DESC: "Gli attacchi base conferiscono al portatore +5% di velocità d'attacco bonus per il resto del combattimento. Questo effetto si accumula.",
        SHIV_NAME: "Pugnale di Statikk",
        SHIV_DESC: "Ogni terzo attacco del portatore infligge 100 danni magici a 3 nemici.",
        DANCER_NAME: "Danzatore fantasma",
        DANCER_DESC: "Il portatore schiva tutti i colpi critici inflitti dagli attacchi base.",
        CURSEDBLADE_NAME: "Lama maledetta",
        CURSEDBLADE_DESC: "Gli attacchi base sul colpo hanno il 20% di probabilità di diminuire di 1 il livello stella del nemico per il resto del combattimento.",
        HYDRA_NAME: "Idra titanica",
        HYDRA_DESC: "Gli attacchi base del portatore infliggono 10% della sua salute massima come danni fisici in un'area a cono dietro il bersaglio.",
        BLADE_NAME: "Lama del re in rovina",
        BLADE_DESC: "AS +20 in più. Il portatore è anche un Maestro d'armi.",
        DEATHCAP_NAME: "Copricapo di Rabadon",
        DEATHCAP_DESC: "Il portatore guadagna +50% amplificazione potenza abilità. Tutte le fonti di potenza abilità sono più efficaci del 50%.",
        ECHO_NAME: "Eco di Luden",
        ECHO_DESC: "Quando il portatore infligge danni con un'abilità, il primo bersaglio colpito e fino a 3 nemici vicini subiscono 180 danni magici ulteriori.",
        LOCKET_NAME: "Medaglione dei Solari di ferro",
        LOCKET_DESC: "All'inizio del combattimento, il portatore e gli alleati nella stessa fila entro 2 esagoni ottengono uno scudo che blocca 250 danni per 6 secondi.",
        SPARK_NAME: "Scintilla di Ionia",
        SPARK_DESC: "Quando un nemico lancia un'abilità, il portatore gli infligge 125 danni puri.",
        MORELLONOMICON_NAME: "Morellonomicon",
        MORELLONOMICON_DESC: "Quando il portatore infligge danni con un'abilità dà fuoco al bersaglio, infliggendo il 20% della salute massima del bersaglio come danni puri per 10 secondi e impedendo qualsiasi cura durante questo intervallo.",
        YUUMI_NAME: "Yuumi",
        YUUMI_DESC: "AP +20 in più. Il portatore è anche uno Stregone.",
        EMBRACE_NAME: "Abbraccio serafico",
        EMBRACE_DESC: "Dopo il lancio di un'abilità, il portatore recupera 20 mana.",
        HEART_NAME: "Fulcro dei geli",
        HEART_DESC: "Riduce la velocità d'attacco dei nemici nelle vicinanze del 30%.",
        HUSH_NAME: "Quiete",
        HUSH_DESC: "Gli attacchi base hanno una probabilità del 33% di silenziare, impedendo al nemico di ottenere mana per 4 secondi.",
        REDEMPTION_NAME: "Redenzione",
        REDEMPTION_DESC: "Quando la salute del portatore scende sotto il 1200%, gli alleati vicini vengono curati di 25 dopo 2,5 secondi. Si attiva una volta per combattimento.",
        DARKIN_NAME: "Darkin",
        DARKIN_DESC: "+20 in più. Il portatore è anche un Demone.",
        THORNMAIL_NAME: "Corazza spinata",
        THORNMAIL_DESC: "Quando il portatore viene colpito da un attacco base, riflette il 100% del danno ridotto come danno magico.",
        BREAKER_NAME: "Spaccaspada",
        BREAKER_DESC: "Gli attacchi base del portatore hanno una probabilità del 25% di disarmare il bersaglio per 4 secondi, impedendogli di infliggere attacchi base.",
        REDBUFF_NAME: "Buff rosso",
        REDBUFF_DESC: "Gli attacchi base del portatore danno fuoco al bersaglio, infliggendo il 20% della salute massima del bersaglio come danni puri per 10 secondi e impedendo qualsiasi cura durante questo intervallo.",
        VOW_NAME: "Voto del cavaliere",
        VOW_DESC: "Armor +20 in più. Il portatore è anche un Cavaliere.",
        CLAW_NAME: "Artiglio del drago",
        CLAW_DESC: "Il portatore ottiene 83% di resistenza ai danni magici.",
        ZEPHYR_NAME: "Zefiro",
        ZEPHYR_DESC: "All'inizio del combattimento, il portatore evoca un turbine nel lato opposto dell'arena che rimuove dal combattimento il nemico più vicino per 5 secondi.",
        HURRICANE_NAME: "Uragano di Runaan",
        HURRICANE_DESC: "MR extra + 20. Gli attacchi base lanciano contro un nemico vicino un proiettile addizionale che infligge danni pari al 75% dell'attacco base del portatore e applica gli effetti sul colpo.",
        ARMOR_NAME: "Armatura di Warmog",
        ARMOR_DESC: "Il portatore rigenera il 6% della salute mancante al secondo.",
        MALLET_NAME: "Martello ghiacciato",
        MALLET_DESC: "Il portatore è anche un Glaciale.",
        FORCE_NAME: "Forza della natura",
        FORCE_DESC: "Il portatore ottiene +1 bonus dimensione massima di squadra."

    };
})();
